name: Node.js CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - uses: johnnybenson/package-json-versioned-action@v1.0.5
        id: package-json
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - run: echo "has-updated -- ${{ steps.package-json.outputs.has-updated }}"

      - name: Build gzips and webpacks
        if: ${{ steps.package-json.outputs.has-updated == 'true'}}
        run: |
          npm ci
          npm run buildAllDist --if-present

      - name: Commit
        if: ${{ steps.package-json.outputs.has-updated == 'true'}}
        run: |
          git config --global user.name 'theBowja'
          git config --global user.email 'theBowja@users.noreply.github.com'
          git add --all
          git commit -am "Automated build for ${{ steps.package-json.outputs.version }}"
          git push