name: publish npm package
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checuout
        uses: actions/checkout@v3

      # Setup .npmrc file to publish to GitHub Packages
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          registry-url: https://npm.pkg.github.com
          # Defaults to the user or organization that owns the workflow file
          scope: "@PaimonApp"
      - name: Build npm package
        run: npm run build
      - name: Publish npm package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.WRITE_PACKAGES_TOKEN }}